# Generated by Django 2.0.5 on 2019-04-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapplication', '0005_auto_20190420_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
